variable "availability_zone" {}
variable "aws_account" {}
variable "aws_region" {}
variable "ec2_ami_type" {}
variable "ec2_instance_type" {}
variable "ec2_recipient_private_ip" {}
variable "ec2_sender_private_ip" {}
variable "ec2_ssh_key_name" {}
variable "ec2_wildcard_private_ip" {}
variable "environment" {}
variable "cidr_all" {}
variable "vpc_cidr" {}
variable "subnet_cidr_block" {}
variable "tags_category" {}
variable "tags_owner" {}