variable "aws_account" {}
variable "aws_region" {}
variable "ec2_ami_type" {}
variable "ec2_instance_type" {}
variable "ec2_ssh_key_name" {}
variable "environment" {}
variable "network_vpc_a_cidr" {}
variable "network_vpc_b_cidr" {}
variable "network_vpc_central_cidr" {}
variable "tags_category" {}
variable "tags_owner" {}
variable "vpc_a_availability_zone" {}
variable "vpc_a_ec2_private_ip" {}
variable "vpc_a_subnet_cidr_block" {}
variable "vpc_b_availability_zone" {}
variable "vpc_b_ec2_private_ip" {}
variable "vpc_b_subnet_cidr_block" {}
variable "vpc_central_availablility_zone_a" {}
variable "vpc_central_availablility_zone_b" {}
variable "vpc_central_subnet_a_cidr" {}
variable "vpc_central_subnet_b_cidr" {}
variable "network_cidr_all" {}
